# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Colin P. Stark
tagline:             'Geoscientist, data analyst & scientific programmer'
description:         'Colin P. Starks''s Homepage'
url:                 '/'
baseurl:             '/'
paginate:            8

# About/contact
author:
  name:             Colin P. Stark
  url:              http://cstarknyc.github.io/
  email:            cstarknyc@gmail.com
