# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Colin P. Stark
tagline:             'Geoscientist and civil engineer'
description:         'Colin P. Starks''s Homepage'
url:                 '/'
baseurl:             '/'
paginate:            8

# About/contact
author:
  name:             Colin P. Stark
  url:              http://cstarkjp.github.io/
  email:            cstarkjp@gmail.com

# Trying to ensure immediate posting of changes
future: true
# # Need to switch to TW if editing there
timezone: JP

# Rerun here: https://github.com/cstarkjp/cstarkjp.github.io/actions/runs/5459527428